### ISSUE TITLE
ARGO - need to restart supervisorctl to push manifest sucessfuly

### ISSUE THREAD

**Issue by lbesnard** [aodn/python-aodncore#71] opened 2018-04-11 01:59 UTC
The argo handler has behaved strangely lately. 

The logs showed that files which should be in the manifest file actually didn't exist on the machine. The reason why was that the path of argo files is usually ```/mnt/ebs/wip/Argo/dac/aoml/profiles/*.nc```, however the logs showed that the ```Argo/dac/``` part was missing from the filepath, even though relative_path_root seems seemed to have the correct value.

I then asked @angus on Thursday morning to restart supervisorctl for argo (a gut feeling). I repushed the same manifest file, no issue whatsoever. The files were found and pushed to s3

**Comment by lwgordonimos** [comment] 2018-04-17 03:10
The root cause is that the handler instance only accepts a string value for the relative path in resolve_params, while the Argo handler needs to dynamically calculate the relative path based on the config value for WIP_DIR. This will need to be resolved by allowing the handler to pass the real calculated path *into* the resolve runner, since the resolve runner has no access back to the handler class, by design, in order to keep everything as much as possible as a "single purpose" class.

The handler will need to pass in the value here: https://github.com/aodn/python-aodncore/blob/master/aodncore/pipeline/handlerbase.py#L728

Such that the resolve runner can access it from here:
https://github.com/aodn/python-aodncore/blob/master/aodncore/pipeline/steps/resolve.py#L87

**Comment by lwgordonimos** [comment] 2018-05-04 05:44
Fixed by https://github.com/aodn/python-aodndata/pull/22

**Closed by lwgordonimos** 2018-05-04 05:44 UTC
Labels: bug
